name = "RiemannEnergy"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["RiemannEnergy"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.8.0"

[[lean_lib]]
name = "RiemannEnergy"

[[lean_exe]]
name = "RiemannEnergyApp"
root = "Main"
